umb/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('umb.admin.urls')),
]

umb/admin/views.py
from django.core import serializers
from django.views.generic.edit import CreateView
from umb.admin.forms import MasterForm, WeightForm
from umb.admin.models import Master, Weight
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.urls.base import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from django.views.generic import View
from django.db.models import Avg, Count, Min, Sum

class LoginFormSet(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

class PasswordChangeFormSet(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

class LoginViewSet(LoginView):
    form_class = LoginFormSet
    redirect_authenticated_user = True
    template_name = 'auth/login.html'
    
class LogoutViewset(LogoutView):
    pass
    
    
class BuyViewSet(LoginRequiredMixin, ListView):
    model = Weight
    paginate_by = 15
    template_name = 'buy.html'

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        qs = super().get_queryset()
        if q is not None:
            return qs.filter(name__icontains=q)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['amount_weight'] = sum(self.get_queryset().values_list('amount_weight', flat=True))
        context['amount_price'] = sum(self.get_queryset().values_list('amount_price', flat=True))
        return context

class WeightViewSet(LoginRequiredMixin, ListView):
    model = Weight
    paginate_by = 5
    template_name = 'weight.html'

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        qs = super().get_queryset()
        if q is not None:
            return qs.filter(name__icontains=q)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['alert'] = Master.objects.filter(key='alert')
        context['discount'] = Master.objects.filter(key='discount')
        context['price'] = Master.objects.filter(key='price')
        return context

class ChangePasswordViewSet(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeFormSet
    template_name = 'change-password.html'
    success_url = reverse_lazy('admin-login')

class CreateWeightViewSet(View):
    def post(self, request):
        if request.is_ajax() and request.method == 'POST':
            form = WeightForm(request.POST)
            if form.is_valid():
                instance = form.save()
                ser_instance = serializers.serialize('json', [ instance, ])
                return JsonResponse({"instance": ser_instance}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=422)
        return JsonResponse({"error": ""}, status=400)

class UpdateWeightViewSet(View):
    def get(self, request):
        if request.is_ajax() and request.method == 'GET':
            instance = Weight.objects.get(id=request.GET.get('id', None))
            if instance:
                ser_instance = serializers.serialize('json', [ instance, ])
                return JsonResponse({"instance": ser_instance}, safe=True, status=200)
            return JsonResponse({"error": "not found"}, status=404)
        return JsonResponse({"error": ""}, status=400)

    def post(self, request):
        if request.is_ajax() and request.method == 'POST':
            instance = Weight.objects.get(id=request.POST.get('id'))
            if instance is not None:
                form = WeightForm(request.POST, instance=instance)
                if form.is_valid():
                    instance = form.save()
                    ser_instance = serializers.serialize('json', [ instance, ])
                    return JsonResponse({"instance": ser_instance}, status=200)
                else:
                    return JsonResponse({"error": form.errors}, status=422)
            return JsonResponse({"error": "not found"}, status=404)
        return JsonResponse({"error": ""}, status=400)
            

class DeleteWeightViewSet(View):
    def get(self, request):
        if request.is_ajax() and request.method == 'GET':
            delete = request.GET.get('id', None)
            if delete is not None:
                Weight.objects.get(id=delete).delete()
                return JsonResponse({},status=204)
            return JsonResponse({},status=404)
        return JsonResponse({},status=400)

class PrintViewset(ListView):
    model = Weight
    template_name = 'print.html'

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        qs = super().get_queryset()
        if q is not None:
            return qs.filter(name__icontains=q)
        return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['amount_weight'] = sum(self.get_queryset().values_list('amount_weight', flat=True))
        context['amount_price'] = sum(self.get_queryset().values_list('amount_price', flat=True))
        return context

class PrintMobileViewset(DetailView):
    model = Weight
    template_name = 'print-mobile.html'


class MasterViewSet(CreateView):
    form_class = MasterForm
    template_name = 'master.html'
    success_url = reverse_lazy('admin-weight')

templates/partials/buy.html
{% load static %}
{% load humanize %}
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <h4 class="text-muted font-weight-bold text-uppercase">Data Pembelian</h4>
        </div>
    </div>
</div>
<div class="row py-5 mx-4">
    <div class="col-12">
        <form action="" class="form-inline mb-2">
            <div class="form-group mr-2">
                <label for="search" class="sr-only">Password</label>
                <input type="text" class="form-control" name="q" id="search" placeholder="Cari..">
            </div>
            <button type="submit" class="btn btn-success">
                Cari
            </button>
        </form>
    </div>
    <div class="col-12" id="printTable">
        <table class="table table-sm table-bordered bg-success text-white text-center">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Lansiran</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Bruto</th>
                    <th scope="col">Tarra</th>
                    <th scope="col">Netto</th>
                    <th scope="col">Potong (%)</th>
                    <th scope="col">Jumlah (Kg)</th>
                    <th scope="col">Harga TBS(TBS/Kg)</th>
                    <th scope="col">Jumlah (Rp)</th>
                    <th scope="col">Lunas</th>
                    <th scope="col">Dibuat</th>
                    <th scope="col">Diperbaharui</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for i in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }} </th>
                    <td>{{ i.alert }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.bruto | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.tara | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.netto | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.discount }}</td>
                    <td>{{ i.amount_weight | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.price | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.amount_price | floatformat:"0" | intcomma }}</td>
                    <td>
                        {% if  i.paid_off %}
                        Lunas
                        {% else %}
                        Belum Lunas
                        {% endif %}
                    </td>
                    <td>{{ i.created_at }}</td>
                    <td>{{ i.updated_at }}</td>
                    <td><a href="{% url 'admin-print-mobile' i.id %}" target="blank" class="text-white">Cetak (POS)</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="px-2 text-success" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                        aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                <li class="page-item"><a class="px-2 text-success" href="#">Page {{ page_obj.number }} of
                        {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="px-2 text-success" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
<div class="row mx-4">
    <div class="col-12 text-left font-weight-bold text-muted">
        <p>Total Jumlah (Kg): {{ amount_weight | floatformat:"0" | intcomma }}</p>
        <p>Total Jumlah (RP): {{ amount_price | floatformat:"0" | intcomma }}</p>
    </div>
    <div class="col-12 text-center">
        <a href="{% url 'admin-print' %}?{{request.GET.urlencode}}" target="blank" class="btn btn-success">Cetak</a>
    </div>
</div>

templates/partials/change-password.html
{% load static %}
{% load i18n static %}
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <h4 class="text-muted font-weight-bold text-uppercase">Ganti Kata Sandi</h4>
        </div>
    </div>
</div>
<div class="row py-5 justify-content-end">
    <div class="col-4 mr-5">
        <div class="card bg-primary">
            <div class="card-body">
                <div class="row">
                    <div class="col-3">
                        <img src="{% static 'img/logo.png' %}" class="img-fluid" height="20" alt="">
                    </div>
                    <div class="col-9 text-center text-white">
                        <p>CV. USAHA MAJU BERSAMA</p>
                        <p>Alamat: Desa Blang Luah, Kac. Darul Makmur, Kab. Nangan Raya, Prov. Aceh</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-5 mr-5">
        <div class="card bg-primary text-white">
            <div class="card-body">
                {% if form.errors %}
                    <p class="text-white">
                    {% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
                    </p>
                {% endif %}
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                        <label for="id_old_password" class="col-sm-6 col-form-label">Kata Sandi Lama</label>
                        <div class="col-sm-6">
                            {{form.old_password}}
                            <span>{{ form.old_password.errors }}</span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_new_password1" class="col-sm-6 col-form-label">Kata Sandi Baru</label>
                        <div class="col-sm-6">
                            {{form.new_password1}}
                            <span>{{ form.new_password1.errors }}</span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_new_password2" class="col-sm-6 col-form-label">Ulangi Kata Sandi Baru</label>
                        <div class="col-sm-6">
                            {{form.new_password2}}
                            <span>{{ form.new_password2.errors }}</span>
                        </div>
                    </div>
                    <button class="btn btn-success btn-block">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/partials/master.html
{% load static %}
{% load i18n static %}
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <h4 class="text-muted font-weight-bold text-uppercase">Ganti Kata Sandi</h4>
        </div>
    </div>
</div>
<div class="row py-5 justify-content-end">
    <div class="col-4 mr-5">
        <div class="card bg-primary">
            <div class="card-body">
                <div class="row">
                    <div class="col-3">
                        <img src="{% static 'img/logo.png' %}" class="img-fluid" height="20" alt="">
                    </div>
                    <div class="col-9 text-center text-white">
                        <p>CV. USAHA MAJU BERSAMA</p>
                        <p>Alamat: Desa Blang Luah, Kac. Darul Makmur, Kab. Nangan Raya, Prov. Aceh</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-5 mr-5">
        <div class="card bg-primary text-white">
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn btn-success">Simpan</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/partials/topbar.html
<div class="h-100">
    <div class="container-fluid h-100">
        <nav>
            <div class="nav nav-tabs border-0" id="nav-tab" role="tablist">
                <a class="nav-link {% if request.resolver_match.url_name == 'admin-weight' %}active{% endif %}" id="nav-one-tab" href="{% url 'admin-weight' %}" role="tab"
                    aria-controls="nav-one  text-muted" aria-selected="true">Penimbangan</a>
                <a class="nav-link {% if request.resolver_match.url_name == 'admin-buy' %}active{% endif %}" id="nav-two-tab" href="{% url 'admin-buy' %}" role="tab"
                    aria-controls="nav-two text-muted" aria-selected="false">Data Pembelian</a>
                <a class="nav-link {% if request.resolver_match.url_name == 'admin-master' %}active{% endif %}" id="nav-two-tab" href="{% url 'admin-master' %}" role="tab"
                    aria-controls="nav-four text-muted" aria-selected="false">Master</a>
                <a class="nav-link {% if request.resolver_match.url_name == 'admin-change-password' %}active{% endif %}" id="nav-three-tab" href="{% url 'admin-change-password' %}" role="button"
                    aria-controls="nav-three text-muted" aria-selected="false">Ganti Kata Sandi</a>
                <a class="nav-link {% if request.resolver_match.url_name == 'admin-logout' %}active{% endif %}" id="nav-three-tab" href="{% url 'admin-logout' %}" role="button"
                    aria-controls="nav-three text-muted" aria-selected="false">Keluar</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade {% if request.resolver_match.url_name == 'admin-weight' %}show active{% endif %}" id="nav-one" role="tabpanel" aria-labelledby="nav-one-tab">
                {% if request.resolver_match.url_name == 'admin-weight' %}{% include 'partials/weight.html' %}{% endif %}
            </div>
            <div class="tab-pane fade {% if request.resolver_match.url_name == 'admin-master' %}show active{% endif %}" id="nav-four" role="tabpanel" aria-labelledby="nav-four-tab">
                {% if request.resolver_match.url_name == 'admin-master' %}{% include 'partials/master.html' %}{% endif %}
            </div>
            <div class="tab-pane fade {% if request.resolver_match.url_name == 'admin-buy' %}show active{% endif %}" id="nav-two" role="tabpanel" aria-labelledby="nav-two-tab">
                {% if request.resolver_match.url_name == 'admin-buy' %}{% include 'partials/buy.html' %}{% endif %}
            </div>
            <div class="tab-pane fade {% if request.resolver_match.url_name == 'admin-change-password' %}show active{% endif %}" id="nav-three" role="tabpanel" aria-labelledby="nav-three-tab">
                {% if request.resolver_match.url_name == 'admin-change-password' %}{% include 'partials/change-password.html' %}{% endif %}
            </div>
        </div>
    </div>
</div>

templates/partials/weight.html
{% load static %}
{% load humanize %}
<div class="row">
    <div class="col-12">
        <div class="text-center">
            <h4 class="text-muted font-weight-bold text-uppercase">Penimbangan</h4>
        </div>
    </div>
</div>
<div class="row pt-5 justify-content-between align-items-center">
    <div class="col-4 ml-5">
        <div>
            <div class="form-group text-center">
                <h4 class="text-muted font-weight-bold text-uppercase">Waktu Sekarang</h4>
                <p>
                    <div class="col">
                        <div id="clock" class="text-muted font-weight-bold"></div>
                    </div>
                </p>
            </div>
        </div>
        <div>
            <div class="form-group row">
                <input type='hidden' id="csrfmiddlewaretoken" name='csrfmiddlewaretoken' value='{{ csrf_token }}' />
                <label for="alert" class="col-3 col-form-label text-muted font-weight-bold">Lansiran</label>
                <div class="col-9">
                    <select name="alert" id="alert" class="form-control" required>
                        {% for obj in alert %}
                            <option value="{{ obj.value }}">{{ obj.value }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="name" class="col-3 col-form-label text-muted font-weight-bold">Nama</label>
                <div class="col-9">
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="discount" class="col-3 col-form-label text-muted font-weight-bold">Potong (%)</label>
                <div class="col-9">
                    <select name="discount" id="discount" class="form-control" required>
                        {% for obj in discount %}
                            <option value="{{ obj.value }}">{{ obj.value }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="price" class="col-3 col-form-label text-muted font-weight-bold">Harga
                    TBS/Kg</label>
                <div class="col-9">
                    <select name="price" id="price" class="form-control" required>
                        {% for obj in price %}
                            <option value="{{ obj.value }}">{{ obj.value }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="paid_off" class="col-3 col-form-label text-muted font-weight-bold">Lunas</label>
                <div class="col-9">
                    <select name="paid_off" id="paid_off" class="form-control" required>
                        <option value="true">Ya</option>
                        <option value="false">Belum Lunas</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <div class="col">
                    <input type="hidden" id="id_perbaharui" name="id_perbaharui">
                    <button type="submit" id="simpan_saja" class="btn btn-success btn-block">Simpan</button>
                    <button type="submit" id="perbaharui" class="btn btn-success btn-block">Perbaharui</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4 mr-5">
        <div>
            <h3 class="text-muted text-center font-weight-bold" id="name_weight"></h3>
        </div>
        <div>
            <div class="form-group">
                <textarea name="netto" id="truck_blank" cols="30" rows="1"
                    class="form-control text-center font-weight-bolder" style="font-size:100px"></textarea>
                <textarea name="bruto" id="truck_fill" cols="30" rows="1" class="form-control text-center font-weight-bolder"
                    style="font-size:100px"></textarea>
                <div class="row py-2">
                    <div class="col">
                        <button id="btn_truck_fill" class="btn btn-success btn-block">TRUCK ISI</button>
                    </div>
                    <div class="col">
                        <button id="btn_truck_blank" class="btn btn-success btn-block">TRUCK KOSONG</button>
                    </div>
                </div>
            </div>
            <div>
                <div class="card bg-primary">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-3">
                                <img src="{% static 'img/logo.png' %}" class="img-fluid" alt="">
                            </div>
                            <div class="col-9 text-center text-white">
                                <p>CV. USAHA MAJU BERSAMA</p>
                                <p>Alamat: Desa Blang Luah, Kac. Darul Makmur, Kab. Nangan Raya, Prov. Aceh</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-inline-block">
        </div>
    </div>
</div>
<div class="row mx-4">
    <div class="col-12">
        <form action="" class="form-inline mb-2">
            <div class="form-group mr-2">
                <label for="search" class="sr-only">Password</label>
                <input type="text" class="form-control" name="q" id="search" placeholder="Cari..">
            </div>
            <button type="submit" class="btn btn-success">
                Cari
            </button>
        </form>
    </div>
    <div class="col-12">
        <table class="table table-sm table-bordered bg-success text-white text-center">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Lansiran</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Bruto</th>
                    <th scope="col">Tarra</th>
                    <th scope="col">Netto</th>
                    <th scope="col">Potong (%)</th>
                    <th scope="col">Jumlah (Kg)</th>
                    <th scope="col">Harga TBS(TBS/Kg)</th>
                    <th scope="col">Jumlah (Rp)</th>
                    <th scope="col">Lunas</th>
                    <th scope="col">Dibuat</th>
                    <th scope="col">Diperbaharui</th>
                    <th scope="col">Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for i in object_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }} </th>
                    <td>{{ i.alert }}</td>
                    <td>{{ i.name }}</td>
                    <td>{{ i.bruto | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.tara | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.netto | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.discount }}</td>
                    <td>{{ i.amount_weight | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.price | floatformat:"0" | intcomma }}</td>
                    <td>{{ i.amount_price | floatformat:"0" | intcomma }}</td>
                    <td>                        
                        {% if  i.paid_off %}
                            Lunas
                        {% else %}
                            Belum Lunas
                        {% endif %}    
                    </td>
                    <td>{{ i.created_at }}</td>
                    <td>{{ i.updated_at }}</td>
                    <td>
                        <button onclick="ubah({{ i.id }})" class="border-0 bg-transparent text-white" id="ubah">Ubah</button> | 
                        <button onclick="hapus({{ i.id }}, '{{ i.name }}')" class="border-0 bg-transparent text-white" id="hapus">Hapus</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-end">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="px-2 text-success" href="?page={{ page_obj.previous_page_number }}" tabindex="-1"
                        aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                <li class="page-item"><a class="px-2 text-success" href="#">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="px-2 text-success" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>